"""
Abstract base classes and core data transfer contracts for Gamer Role Classification.
Enables pluggable rule evaluators and allows zero-friction replacement with ML models.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from app.core.role_classifier.config import RoleClassificationConfig
from app.core.role_classifier.features import GamerRoleFeatures


@dataclass(frozen=True)
class RuleEvaluation:
    """
    Detailed evaluation output from an individual role rule across all 4 input signals.
    """
    role_name: str
    affinity_score: float  # Composite affinity (0.0 to 100.0)
    dna_score: float       # Trait alignment (0.0 to 100.0)
    stats_score: float     # In-game stats alignment (0.0 to 100.0)
    preference_score: float # Stated role preference alignment (0.0 to 100.0)
    game_score: float      # Preferred game & character alignment (0.0 to 100.0)
    reasoning_snippet: str # Explainable justification for this specific role


@dataclass(frozen=True)
class RoleClassificationResult:
    """
    Final output generated by the Role Classification Engine:
    - Primary Role
    - Secondary Role
    - Confidence Score (0.0 to 1.0)
    - Reasoning (Explainable AI breakdown)
    Plus complete role affinity distributions and feature audit data.
    """
    primary_role: str
    secondary_role: str
    confidence_score: float
    reasoning: str
    personality: str
    role_affinities: dict[str, float]
    signal_contributions: dict[str, dict[str, float]] = field(default_factory=dict)
    feature_importance: dict[str, float] = field(default_factory=dict)


class BaseRoleRule(ABC):
    """
    Abstract contract for an individual role classification rule.
    Each rule assesses how strongly the multi-signal inputs corroborate a specific role.
    """

    def __init__(self, name: str, description: str) -> None:
        self.name = name
        self.description = description

    @abstractmethod
    def evaluate(
        self,
        features: GamerRoleFeatures,
        config: RoleClassificationConfig,
    ) -> RuleEvaluation:
        """
        Calculates role affinity from DNA, stats, preferences, and games.
        Must return a RuleEvaluation with individual signal scores and reasoning.
        """
        pass

    def calculate_preference_score(
        self,
        preferred_roles: list[str],
        config: RoleClassificationConfig,
    ) -> float:
        """
        Calculates affinity based on user's stated preferred roles.
        Returns 100.0 for exact/synonym match, 0.0 otherwise.
        """
        if not preferred_roles:
            return 50.0  # Neutral prior if no preference declared

        synonyms = config.ROLE_SYNONYMS.get(self.name, [self.name.lower()])
        for pref in preferred_roles:
            clean_pref = pref.strip().lower()
            if clean_pref in synonyms or self.name.lower() in clean_pref:
                return 100.0

        return 20.0  # Mild negative penalty if explicit other roles preferred

    def calculate_game_context_score(
        self,
        preferred_games: list[str],
        favorite_heroes: list[str],
        config: RoleClassificationConfig,
    ) -> float:
        """
        Calculates affinity based on preferred games and hero/agent pool.
        """
        if not preferred_games and not favorite_heroes:
            return 50.0  # Neutral prior

        matched_hero_count = 0
        total_heroes = max(1, len(favorite_heroes))

        for game in preferred_games:
            game_key = game.strip().lower()
            role_heroes = config.GAME_HERO_AFFINITIES.get(game_key, {}).get(self.name, [])
            for hero in favorite_heroes:
                if hero.strip().lower() in role_heroes:
                    matched_hero_count += 1

        if favorite_heroes:
            hero_match_ratio = matched_hero_count / total_heroes
            return round(40.0 + (hero_match_ratio * 60.0), 2)

        return 50.0


class BaseRoleClassifier(ABC):
    """
    Abstract interface for Gamer Role Classifiers.
    Defines the contract implemented by both rule-based engines and future ML models.
    """

    @abstractmethod
    def classify(self, features: GamerRoleFeatures) -> RoleClassificationResult:
        """
        Executes classification over the 4 inputs:
        1. Gamer DNA feature vector
        2. Official game statistics
        3. Preferred roles
        4. Preferred games

        Returns Primary Role, Secondary Role, Confidence Score, and Reasoning.
        """
        pass
